# nodejs
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-nodejs-deploy
  labels:
    app: front-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-nodejs
  template:
    metadata:
      name: front-nodejs
      labels:
        app: front-nodejs
    spec:
      initContainers:
        - name: init-mariadb-check
          image: mariadb:10.11.9-jammy
          command: [ 'sh', '-c', 'until mysqladmin ping -h mariadb --silent; do echo "Waiting for MariaDB..."; sleep 2; done' ]
      containers:
        - name: front-nodejs
          image: {{ .Values.deployment.nodejs.image }}
          ports:
            - containerPort: 3000
          env:
            - name: REGISTER_URL
              value: msa-register-service:30100
            - name: PAYMENT_URL
              value: msa-payment-service:30200
            - name: PARKING_URL
              value: msa-parking-service:30300
            - name: STATISTICS_URL
              value: msa-statistics-service:30400
      nodeSelector:
        node-type: worker  # Worker 노드에서 실행하도록 설정
      tolerations:
        - key: "node-type"
          operator: "Equal"
          value: "worker"
          effect: "NoSchedule"
---
# nodejs
apiVersion: v1
kind: Service
metadata:
  name: front-nodejs-svc
spec:
  selector:
    app: front-nodejs
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
