# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  register:
    image: docker.io/yoon741/msa-register-service
  payment:
    image: ashashrain/parking-payment-service:v4
  parking:
    image: docdker/parking
  statistics:
    image: snicuz0588/msa-statistics-service:v5
  nodejs:
    image: docker.io/dangdang42/front-nodejs:v32
    ip: 43.200.71.227
  nginx:
    image: docker.io/dangdang42/front-nginx:v14