# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  register:
    image: docker.io/yoon741/msa_register_service:v2
  payment:
    image: docker.io/ashashrain/parking-payment-service:v5
  parking:
    image: docdker/parking
  statistics:
    image: snicuz0588/msa-statistics-service:v6
  nodejs:
    image: dangdang42/front-nodejs:v40
    ip: 3.37.31.226
  nginx:
    image: dangdang42/front-nginx:v17